(function(root){'use strict';
const keys=['kcal','protein','carbs','fat'],meals=['Petit-déjeuner','Déjeuner','Dîner','Collation'];
function empty(){return {version:1,foods:[],favorites:[],entries:[],recipes:[],goals:{kcal:null,protein:null,carbs:null,fat:null}};}
const number=v=>v!==null&&v!==undefined&&v!==''&&Number.isFinite(Number(v))?Number(v):null;
function validFood(f){return f&&typeof f.id==='string'&&typeof f.name==='string'&&f.name.trim().length>0&&f.name.length<=250&&['g','ml'].includes(f.unit)&&keys.every(k=>f[k]===null||(Number.isFinite(f[k])&&f[k]>=0&&f[k]<=(k==='kcal'?1000:100)));}
function complete(f){return validFood(f)&&keys.every(k=>Number.isFinite(f[k]));}
function portion(f,q){if(!complete(f)||!Number.isFinite(q)||q<=0||q>10000)throw new Error('Aliment ou quantité invalide.');return Object.fromEntries(keys.map(k=>[k,f[k]*q/100]));}
function totals(entries){return entries.reduce((sum,e)=>{const p=portion(e.food,e.quantity);for(const k of keys)sum[k]+=p[k];return sum;},Object.fromEntries(keys.map(k=>[k,0])));}
function validate(n){const date=d=>typeof d==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(d)&&!Number.isNaN(Date.parse(d));const entry=e=>e&&complete(e.food)&&Number.isFinite(e.quantity)&&e.quantity>0&&e.quantity<=10000;
return n&&n.version===1&&Array.isArray(n.foods)&&n.foods.length<=10000&&n.foods.every(validFood)&&Array.isArray(n.favorites)&&n.favorites.every(id=>typeof id==='string')&&Array.isArray(n.entries)&&n.entries.length<=100000&&n.entries.every(e=>typeof e.id==='string'&&date(e.date)&&meals.includes(e.meal)&&entry(e))&&Array.isArray(n.recipes)&&n.recipes.length<=1000&&n.recipes.every(r=>typeof r.id==='string'&&typeof r.name==='string'&&r.name.length<=120&&Array.isArray(r.items)&&r.items.length>0&&r.items.length<=100&&r.items.every(entry))&&n.goals&&keys.every(k=>n.goals[k]===null||(Number.isFinite(n.goals[k])&&n.goals[k]>0&&n.goals[k]<=(k==='kcal'?15000:1000)));}
function fromOFF(p){if(!p||!p.code)return null;const n=p.nutriments||{},energy=number(n['energy-kcal_100g'])??(number(n['energy-kj_100g'])!==null?number(n['energy-kj_100g'])/4.184:null);const f={id:'off:'+String(p.code),name:String(p.product_name_fr||p.product_name||'Produit '+p.code).slice(0,250),brand:String(p.brands||'').slice(0,120),source:'Open Food Facts',sourceUrl:'https://world.openfoodfacts.org/product/'+encodeURIComponent(p.code),unit:p.nutrition_data_per==='100ml'?'ml':'g',kcal:energy,protein:number(n.proteins_100g),carbs:number(n.carbohydrates_100g),fat:number(n.fat_100g)};return validFood(f)?f:null;}
const normalize=s=>String(s).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/œ/g,'oe').replace(/æ/g,'ae').replace(/[’']/g,' ');
function search(foods,query,limit=50){const words=normalize(query).trim().split(/\s+/).filter(Boolean);if(!words.length)return [];return foods.filter(f=>words.every(w=>normalize(f.name+' '+(f.brand||'')).includes(w))).sort((a,b)=>normalize(a.name).indexOf(normalize(query))-normalize(b.name).indexOf(normalize(query))||a.name.localeCompare(b.name,'fr')).slice(0,limit);}
root.RepereNutritionCore={keys,meals,empty,validFood,complete,portion,totals,validate,fromOFF,search};if(typeof module!=='undefined')module.exports=root.RepereNutritionCore;
})(typeof window!=='undefined'?window:globalThis);
